Repository gdsc-gvp/DSA, pull requests merged in 2021-10, with the labels that each got.

#13 Update community.yml
  .github/workflows/community.yml
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest

#21 Added Quicksort Algo
  Sorting/Quicksort/Quicksort.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#23 Create main.py in SelectionSort
  Sorting/SelectionSort/main.py
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#24 Insertion Sort
  Sorting/insertion_sort.c
Labels: hacktoberfest-accepted, Hacktoberfest

#32 Linear_Search Algo
  Searching/Linear_Search/Linear_Search.cpp
Labels: approved, Hacktoberfest

#37 implemented linear search in c language
  Searching/Linear_Search/Linear_search.c
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#34 Adding BFS and DFS traversal in Graphs in c++
  Graphs/BFS Traversal/BFS.cpp
  Graphs/DFS Traversal/DFS.cpp
Labels: Hacktoberfest

#38 Added Merge sort Algorithm
  Sorting/MergeSort/Mergesort.cpp
Labels: Hacktoberfest

#42 Added Binary search algorithm in python
  Searching/Binary_Search/BinarySearch.py
  Searching/Linear_Search/LinearSearch.py
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#45 Added Bubble Sort algorithm
  Sorting/BubbleSort/BubbleSort.py
Labels: approved, Hacktoberfest

#41 Merge Sort in c
  Sorting/MergeSort/MergeSort.c
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#54 Binary Search Algo
  Searching/Binary_Search/BinarySearch.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#53 Add Shell Sort using Python (Issue #49)
  Sorting/ShellSort/ShellSort.py
Labels: approved, Hacktoberfest

#59 Linear Search in Java
  Searching/Linear_Search/LinearSearch.java
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#56 Stack using Array
  Stacks/Stack Using Array.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#60 Create reverseLinkedList.cpp
  LinkedList/reverseLinkedList.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#63 Counting Sort
  Sorting/Counting Sort/counting_sort.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#57 Add Quicksort Python Implementation
  Sorting/Quicksort/Quicksort.py
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#67 Binary Search in C language
  Searching/Binary_Search/BinarySearch.c
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#70 Binary Search in Java language #33
  Searching/Binary_Search/BinarySearch.java
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#80 Update community.yml
  .github/workflows/community.yml
Labels: hacktoberfest-accepted, Hacktoberfest

#69 Bubble Sort in C++ and Java
  Sorting/BubbleSort/BubbleSort.c++
  Sorting/BubbleSort/BubbleSort.java
Labels: approved, Hacktoberfest

#72 Implementation of Queue using array
  Queue/Implementation_of_queue_using_array/Implementation_of_queue_using_array.cpp
Labels: approved, Hacktoberfest

#82 Added Tarjan's Algorithm Implementation
  Graphs/Tarjans_Algorithm/Tarjans_Algorithm.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#76 Added Queue Algo
  Queue/QueueImp.java
  Queue/Readme.md
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#81 Added AVL Tree implementation
  Tree/AVL_Trees/AVL_Tree.c
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#71 Stack Using Linked List
  Stacks/Stack_Using_LInkedList.cpp
Labels: Hacktoberfest

#83 Updated Stack using array
  Stacks/Stack Using Array.cpp
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#98 updated PR Template
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#86 Added Kosaraju's Algorithm
  Graphs/Kosarajus_Algorithm/Kosarajus_Algorithm.cpp
Labels: approved, Hacktoberfest

#87 Added the bubble sort algorithm implementation in C
  Sorting/BubbleSort/BubbleSort.c
Labels: approved, Hacktoberfest

#88 Added Krushkal's Algorithm Implementation
  Graphs/Krushkals_Algorithm/Krushkals_Algorithm.cpp
Labels: approved

#99 Heap Sort.
  Sorting/Heap sort/heapsort.py
Labels: hacktoberfest-accepted, approved, Hacktoberfest

#96 Added Bst
  BST/Readme.md
  BST/binarysearchtree.cpp
Labels: hacktoberfest-accepted, approved

#100 heapsort algorithm uploaded
  Sorting/HeapSort/HeapSort.cpp
Labels: approved

#94 add java implementation of counting sort
  Sorting/Counting Sort/counting_sort.java
Labels: approved

#127 Added Insertion sort in cpp
  Sorting/Insertion Sort/Insertion_sort.cpp
Labels: tobereviewed

#131 postorder Traversal of binary tree
  Tree/Binary_Tree/Inorder_Traversal/inorder_traversal.cpp
  Tree/Binary_Tree/postorder_traversal/postorder_traversal.cpp
  Tree/Binary_Tree/preorder_Traversal/inorder_traversal.cpp
Labels: tobereviewed

#129 Inorder Traversal of Binary_Tree added
  Tree/Binary_Tree/Inorder_Traversal/inorder_traversal.cpp
Labels: tobereviewed

#132 Added merge__sort in python
  Sorting/MergeSort/merge_sort.py
Labels: tobereviewed
